Repository umair9747/headmail, pull requests merged in 2021-10, with the labels that each got.

#3 Update banner.js
  functions/banner.js
Labels: haktoberfest-accepted

#4 Update process.js
  functions/process.js
Labels: haktoberfest-accepted, haktoberfest

#6 Update README.md
  README.md
Labels: Hacktoberfest-accepted, Hacktoberfest
